'use client';

import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useRef } from 'react';

export default function Home() {
  // Get the canvas node and the drawing context
  const canvas = useRef(null);

  useEffect(() => {
    const context = canvas.current.getContext('2d');

    const width = document.body.offsetWidth;
    const height = document.body.offsetHeight;
    canvas.current.width = width;
    canvas.current.height = height;

    context.fillStyle = '#000';
    context.fillRect(0, 0, width, height);

    // calculate how many 'lines' to show and animate
    const columns = Math.floor(width / 20) + 1;
    const yPositions = Array.from({ length: columns }).fill(0);

    context.fillStyle = '#000';
    context.fillRect(0, 0, width, height);

    const matrixEffect = () => {
      context.fillStyle = '#0001';
      context.fillRect(0, 0, width, height);

      context.fillStyle = '#0f0';
      context.font = '15pt monospace';

      yPositions.forEach((y, index) => {
        const text = String.fromCharCode(Math.random() * 128);
        const x = index * 20;
        context.fillText(text, x, y);

        if (y > 100 + Math.random() * 10000) {
          yPositions[index] = 0;
        } else {
          yPositions[index] = y + 20;
        }
      });
    };

    const interval = setInterval(matrixEffect, 50);
    return () => {
      clearInterval(interval);
    };
  }, [canvas]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex-1 flex-col justify-center items0center min-h-[100vh] px-0 py-[2rem]'>
        <hgroup className='relative flex justify-center align-center'>
          <canvas
            width='500'
            height='200'
            className='relative w-[300px] h-[200px]'
            ref={canvas}
          />
          <h1 className='text-[3.5rem] absolute'>Jiyuun Yang</h1>
        </hgroup>
        <main className='flex-col ml-10'>
          <section className='flex-col'>
            <h2 className='mt-[2rem] text-[#58936f] text-[1.5rem]'>Profile</h2>
            <h3>
              <Link href='https://github.com/jiyuunyang'>Github</Link>
            </h3>
            <h3>
              <Link href='https://jiyuunyang.tistory.com/'>Blog</Link>
            </h3>
            <h3>
              <Link href='https://jiyuunyang.github.io/keynote/'>
                Portfolio
              </Link>
            </h3>
          </section>
          <section className='flex-col'>
            <h2 className='mt-[2rem] text-[#58936f] text-[1.5rem]'>Projects</h2>
            <h3>
              <Link href='/tree-deco'>나만의 트꾸 2024.12</Link>
            </h3>
            <h3>
              <Link href='https://happywebzine.netlify.app/'>
                해피구독 | Koldsleep 2022.11
              </Link>
            </h3>
            <h3>
              <Link href='https://github.com/codestates/MuscleFormula'>
                근의 공식 | Codestates 2022.04
              </Link>
            </h3>
            <h3>
              <Link href='https://github.com/codestates/Music-Flower'>
                Music Flower | Codestates 2022.03
              </Link>
            </h3>
          </section>
        </main>
      </div>
    </>
  );
}
