import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useEffect, useRef } from 'react';

export default function Home() {
  // Get the canvas node and the drawing context
  const canvas = useRef();

  useEffect(() => {
    const context = canvas.current.getContext('2d');

    const width = document.body.offsetWidth;
    const height = document.body.offsetHeight;
    canvas.current.width = width;
    canvas.current.height = height;

    context.fillStyle = '#000';
    context.fillRect(0, 0, width, height);

    // calculate how many 'lines' to show and animate
    const columns = Math.floor(width / 20) + 1;
    const yPositions = Array.from({ length: columns }).fill(0);

    context.fillStyle = '#000';
    context.fillRect(0, 0, width, height);

    const matrixEffect = () => {
      context.fillStyle = '#0001';
      context.fillRect(0, 0, width, height);

      context.fillStyle = '#0f0';
      context.font = '15pt monospace';

      yPositions.forEach((y, index) => {
        const text = String.fromCharCode(Math.random() * 128);
        const x = index * 20;
        context.fillText(text, x, y);

        if (y > 100 + Math.random() * 10000) {
          yPositions[index] = 0;
        } else {
          yPositions[index] = y + 20;
        }
      });
    };

    const interval = setInterval(matrixEffect, 50);
    return () => {
      clearInterval(interval);
    };
  }, [canvas]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <section className={styles.headline}>
          <canvas
            width='500'
            height='200'
            className={styles.canvas}
            ref={canvas}
          />
          <h1 className={styles.title}>Jiyuun Yang</h1>
        </section>
        <section className={styles.description}>
          <h2 className={styles.theme}>Profile</h2>
          <article className={styles.detail}>
            <Link href='https://github.com/jiyuunyang'>personal Github</Link>
            <Link href='https://github.com/piyuun'>Github for work</Link>
            <Link href='https://jiyuunyang.tistory.com/'>Blog</Link>
          </article>
          <h2 className={styles.theme}>Works</h2>
          <h3 className={styles.item}>DataB 2021.06 - </h3>
          <article className={styles.detail}>
            <Link href='https://www.engram.us'>Engram</Link>
            <Link href='https://blog.engram.us'>Engram Blog</Link>
          </article>
          <h3 className={styles.item}>Koldsleep 2022.10 - 2022.12</h3>
          <article className={styles.detail}>
            <Link href='https://play.google.com/store/apps/details?id=com.maiorem00.happysavefronttest&hl=ko&pli=1'>
              Happy Safe Box
            </Link>
            <Link href='https://happywebzine.netlify.app/'>해피구독</Link>
          </article>
          <h3 className={styles.item}>Codestates 2022.03 - 2022.04</h3>
          <article className={styles.detail}>
            <Link href='https://github.com/codestates/MuscleFormula'>
              근의 공식
            </Link>
            <Link href='https://github.com/codestates/Music-Flower'>
              Music Flower
            </Link>
          </article>
        </section>
      </main>
    </div>
  );
}
